<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-03-23T12:49:49 IST" name="Suite" finished-at="2023-03-23T12:50:39 IST" duration-ms="49904">
    <groups>
      <group name="smokesuite">
        <method signature="CreateContactwithOrganizationTest.Createcontactwithorganization_TC_01()[pri:0, instance:vTiger.contactsTest.CreateContactwithOrganizationTest@9f116cc]" name="Createcontactwithorganization_TC_01" class="vTiger.contactsTest.CreateContactwithOrganizationTest"/>
      </group> <!-- smokesuite -->
    </groups>
    <test started-at="2023-03-23T12:49:49 IST" name="Test" finished-at="2023-03-23T12:50:39 IST" duration-ms="49904">
      <class name="vTiger.contactsTest.CreateContactwithOrganizationTest">
        <test-method signature="Createcontactwithorganization_TC_01()[pri:0, instance:vTiger.contactsTest.CreateContactwithOrganizationTest@9f116cc]" started-at="2023-03-23T12:49:49 IST" name="Createcontactwithorganization_TC_01" finished-at="2023-03-23T12:50:39 IST" duration-ms="49834" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at vTiger.contactsTest.CreateContactwithOrganizationTest.Createcontactwithorganization_TC_01(CreateContactwithOrganizationTest.java:134)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Createcontactwithorganization_TC_01 -->
      </class> <!-- vTiger.contactsTest.CreateContactwithOrganizationTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
